theme = "light:monokai-custom-light.theme,dark:monokai-custom.theme"
font-family = "Hack Nerd Font Mono Bsrc"
font-size = 14
macos-titlebar-style = "tabs"
window-theme = "ghostty"
maximize = true
cursor-style = block
cursor-style-blink = false
app-notifications = false

# Keep shell integration enabled for local and SSH sessions.
shell-integration-features = ssh-terminfo,ssh-env,no-cursor
