local keymap = vim.keymap.set

keymap("n", "<leader>w", "<cmd>write<cr>")
keymap("n", "<leader>q", "<cmd>quit<cr>")
keymap("n", "<leader>?", "<cmd>BsrcHelp<cr>", { desc = "Bsrc help" })
keymap("n", "[d", vim.diagnostic.goto_prev, { desc = "Previous diagnostic" })
keymap("n", "]d", vim.diagnostic.goto_next, { desc = "Next diagnostic" })
keymap("n", "<leader>vd", vim.diagnostic.open_float, { desc = "Line diagnostics" })
keymap("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", { desc = "Diagnostics list" })
keymap("n", "<leader>xr", "<cmd>Trouble lsp_references toggle<cr>", { desc = "References list" })
keymap("n", "<leader>xs", "<cmd>Trouble symbols toggle focus=false<cr>", { desc = "Symbols list" })
keymap("n", "<leader>o", "<cmd>AerialToggle!<cr>", { desc = "Outline" })

keymap("v", "J", ":m '>+1<CR>gv=gv")
keymap("v", "K", ":m '<-2<CR>gv=gv")
keymap("n", "J", "mzJ`z")
keymap("n", "<C-d>", "<C-d>zz")
keymap("n", "<C-u>", "<C-u>zz")
keymap("n", "n", "nzzzv")
keymap("n", "N", "Nzzzv")
keymap("n", "Q", "<nop>")

keymap({ "n", "v" }, "<leader>y", [["+y]])
keymap("n", "<leader>Y", [["+Y]])
keymap({ "n", "v" }, "<leader>d", [["_d]])
keymap("x", "<leader>p", [["_dP]])
keymap("n", "<leader>n", "<cmd>bnext<cr>")
keymap("n", "<leader>p", "<cmd>bprevious<cr>")
keymap("n", "<leader>x", "<cmd>bdelete<cr>")
keymap("n", "<leader>ml", "<cmd>b#<cr>")
keymap("n", "<leader>L", "<cmd>BufferLineMovePrev<cr>", { desc = "Move buffer left" })
keymap("n", "<leader>R", "<cmd>BufferLineMoveNext<cr>", { desc = "Move buffer right" })
keymap("i", "<C-c>", "<Esc>")
