#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["python-frontmatter>=1.1"]
# ///
"""Generate reading-list/<kind>.md from notes/<kind>/ entries with read=false.

Output layout:
  - For dated kinds (paper, article, youtube): grouped by `## YYYY` descending.
  - For undated kinds (blog, github): single ungrouped list sorted by `created:`.

Each entry: `- [[notes/<kind-plural>/<basename-no-ext>|Title]] — Authors et al.`

Examples:
    ks_reading_list.py --kind paper
    ks_reading_list.py --all
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _ks_common import (  # noqa: E402
    KIND_TO_PLURAL,
    find_vault,
    info,
    now_iso,
    read_frontmatter,
    reading_list_path,
    warn,
    write_frontmatter,
)

KINDS = ("paper", "article", "youtube", "blog", "github", "course")
DATED_KINDS = {"paper", "article", "youtube"}


def _format_authors(authors: list | None) -> str:
    if not authors or not isinstance(authors, list):
        return ""
    cleaned = [str(a).strip() for a in authors if str(a).strip()]
    if not cleaned:
        return ""
    if len(cleaned) == 1:
        return cleaned[0]
    if len(cleaned) == 2:
        return f"{cleaned[0]} & {cleaned[1]}"
    return f"{cleaned[0]} et al."


def _entry_line(kind: str, meta: dict, basename: str) -> str:
    plural = KIND_TO_PLURAL[kind]
    stem = basename.removesuffix(".md")
    title = str(meta.get("title") or stem).strip()
    authors_str = _format_authors(meta.get("authors"))
    if kind == "paper":
        suffix = f" — {authors_str}" if authors_str else ""
        return f"- [[notes/{plural}/{stem}|{title}]]{suffix}"
    if kind == "article":
        author = meta.get("author") or authors_str
        publication = meta.get("publication") or ""
        bits = [b for b in (str(author or ""), str(publication)) if b]
        suffix = f" — {' · '.join(bits)}" if bits else ""
        return f"- [[notes/{plural}/{stem}|{title}]]{suffix}"
    if kind == "youtube":
        channel = str(meta.get("channel") or "").strip()
        suffix = f" — {channel}" if channel else ""
        return f"- [[notes/{plural}/{stem}|{title}]]{suffix}"
    if kind == "blog":
        author = str(meta.get("author") or "").strip()
        suffix = f" — {author}" if author else ""
        return f"- [[notes/{plural}/{stem}|{title}]]{suffix}"
    if kind == "github":
        desc = str(meta.get("description") or "").strip()
        suffix = f" — {desc}" if desc else ""
        return f"- [[notes/{plural}/{stem}|{title}]]{suffix}"
    if kind == "course":
        instructor = str(meta.get("instructor") or "").strip()
        institution = str(meta.get("institution") or "").strip()
        bits = [b for b in (instructor, institution) if b]
        suffix = f" — {' · '.join(bits)}" if bits else ""
        return f"- [[notes/{plural}/{stem}|{title}]]{suffix}"
    return f"- [[notes/{plural}/{stem}|{title}]]"


def render_dated(kind: str, entries: list[tuple[dict, str]]) -> tuple[str, int]:
    by_year: dict[int | None, list[tuple[dict, str]]] = defaultdict(list)
    for meta, basename in entries:
        year = meta.get("year")
        if isinstance(year, int):
            by_year[year].append((meta, basename))
        else:
            by_year[None].append((meta, basename))

    ordered_years = sorted([y for y in by_year if y is not None], reverse=True)
    has_undated = None in by_year

    plural = KIND_TO_PLURAL[kind]
    lines = [f"# Reading list — {plural}", ""]
    unread_count = sum(len(v) for v in by_year.values())
    lines.append(
        f"*{unread_count} unread {plural}. "
        f"Generated by `ks_reading_list.py` — do not edit by hand.*"
    )
    lines.append("")
    if unread_count == 0:
        lines.append(f"_No unread {plural}._")
        lines.append("")
        return "\n".join(lines), 0

    for year in ordered_years:
        lines.append(f"## {year}")
        lines.append("")
        for meta, basename in sorted(by_year[year], key=lambda mb: str(mb[0].get("title") or mb[1])):
            lines.append(_entry_line(kind, meta, basename))
        lines.append("")
    if has_undated:
        lines.append("## Undated")
        lines.append("")
        for meta, basename in sorted(by_year[None], key=lambda mb: str(mb[0].get("title") or mb[1])):
            lines.append(_entry_line(kind, meta, basename))
        lines.append("")
    return "\n".join(lines), unread_count


def render_flat(kind: str, entries: list[tuple[dict, str]]) -> tuple[str, int]:
    plural = KIND_TO_PLURAL[kind]
    lines = [f"# Reading list — {plural}", ""]
    unread_count = len(entries)
    lines.append(
        f"*{unread_count} unread {plural}. "
        f"Generated by `ks_reading_list.py` — do not edit by hand.*"
    )
    lines.append("")
    if unread_count == 0:
        lines.append(f"_No unread {plural}._")
        lines.append("")
        return "\n".join(lines), 0

    for meta, basename in sorted(
        entries,
        key=lambda mb: (str(mb[0].get("created") or ""), str(mb[0].get("title") or mb[1])),
        reverse=True,
    ):
        lines.append(_entry_line(kind, meta, basename))
    lines.append("")
    return "\n".join(lines), unread_count


def collect(vault: Path, kind: str) -> list[tuple[dict, str]]:
    plural = KIND_TO_PLURAL[kind]
    d = vault / "notes" / plural
    if not d.is_dir():
        return []
    out: list[tuple[dict, str]] = []
    for md in sorted(d.glob("*.md")):
        try:
            meta, _ = read_frontmatter(md)
        except Exception as exc:
            warn(f"skipping unparseable {md}: {exc}")
            continue
        if meta.get("type") != "note":
            continue
        if meta.get("kind") != kind:
            continue
        if meta.get("read") is True:
            continue
        out.append((meta, md.name))
    return out


def regen_one(vault: Path, kind: str) -> tuple[int, int]:
    entries = collect(vault, kind)
    if kind in DATED_KINDS:
        body, count = render_dated(kind, entries)
    else:
        body, count = render_flat(kind, entries)

    plural = KIND_TO_PLURAL[kind]
    target = reading_list_path(vault, plural)
    target.parent.mkdir(parents=True, exist_ok=True)

    page_meta = {
        "type": "reading-list",
        "kind": plural,
        "generated": now_iso(),
        "unread_count": count,
    }
    write_frontmatter(target, page_meta, body)
    info(f"wrote: {target.relative_to(vault)} ({count} unread)")
    return len(entries), count


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--kind", choices=KINDS, help="generate one kind only")
    p.add_argument("--all", action="store_true", help="generate every kind")
    args = p.parse_args(argv)

    vault = find_vault().path
    info(f"vault: {vault}")

    if not args.kind and not args.all:
        p.error("must pass --kind <K> or --all")

    targets = list(KINDS) if args.all else [args.kind]
    for k in targets:
        regen_one(vault, k)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
